[package]
name = "alice-http"
version = "1.0.1"
edition = "2021"
authors = ["Moroya Sakamoto <sakamoro@alicelaw.net>"]
license = "AGPL-3.0-or-later"
description = "Pure Rust HTTP/1.1 and HTTP/2 parser and framework"
repository = "https://github.com/ext-sakamoro/ALICE-HTTP"
keywords = ["http", "http2", "parser", "server", "client"]
categories = ["network-programming", "web-programming::http-server", "parser-implementations"]

[lib]
crate-type = ["rlib"]
